blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/comment/', views.post_comment, name='post_comment'),
]

mainpage/urls.py
from django.urls import path
from . import views

app_name = 'mainpage'

urlpatterns = [
    path('', views.home, name="home"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainpage.urls', namespace='mainpage')),
    path('blog/', include('blog.urls', namespace='blog')),
]

blog/models.py
from django.db import models
from django.db.models.query import QuerySet
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self) -> QuerySet:
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)


class Post(models.Model):

    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,
                            unique_for_date='publish')
    author = models.ForeignKey(User,
                               on_delete = models.CASCADE,
                               related_name = 'blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2,
                              choices = Status.choices,
                              default = Status.DRAFT)
    objects = models.Manager() # The default manager.
    published = PublishedManager() # Our custom manager.
    tags = TaggableManager()

    class Meta:
        ordering = ['-publish']
        indexes = [
            models.Index(fields=['-publish']),
        ]

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year,
                                                 self.publish.month,
                                                 self.publish.day,
                                                 self.slug])
    

class Comment(models.Model):
    post = models.ForeignKey(Post,
                             on_delete = models.CASCADE,
                             related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created']
        indexes = [
            models.Index(fields=['created']),
        ]

    def __str__(self):
        return f"Comment by {self.name} on {self.post}"

mainpage/models.py
from django.db import models

# Create your models here.

blog/forms.py
from .models import Comment
from django.forms import ModelForm

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment
from django.http import Http404

from django.views.generic import ListView
from .forms import CommentForm
from django.views.decorators.http import require_POST

def post_list(request):
    posts = Post.published.all()
    context = {
        'posts' : posts
    }
    return render(request, 'blog/post/list.html', context)


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post,
                             slug=post,
                             publish__year = year,
                             publish__month = month,
                             publish__day = day,
                             status=Post.Status.PUBLISHED)
    
    comments = post.comments.filter(active=True)
    form = CommentForm()

    context = {
        'post':post,
        'comments':comments,
        'form':form,
    }
    return render(request, 'blog/post/detail.html', context)


@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post,
                             id=post_id,
                             status = Post.Status.PUBLISHED)
    comment = None

    form = CommentForm(request.POST)
    
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()

    context = {
        'post':post,
        'form':form,
        'comment':comment
    }
    
    return render(request, 'blog/post/comment.html', context)

mainpage/views.py
from django.shortcuts import render

def home(request):
    context={}
    return render(request, 'home.html', context)

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static "css/blog.css" %}" rel="stylesheet">
</head>
<body>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
    <div id="sidebar">
    </div>
</body>
</html>

blog/templates/blog/post/comment.html
{% extends "blog/base.html" %}

{% block title %}Add a Comment{% endblock title %}

{% block content %}
    {% if comment %}
        <h2>Your comment has been added.</h2>
        <p><a href="{{post.get_absolute_url}}">Back to the post</a></p>
    {% else %}
        {% include "blog/post/includes/comment_form.html" %}
    {% endif %}
{% endblock content %}

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}

{% block title %}
    {{ post.title }}
{% endblock %}

{% block content %}

    <h1>{{ post.title }}</h1>
    
    <p class="date">
        Published {{ post.publish }} by {{ post.author }}
    </p>
    
    {{ post.body|linebreaks }}


    {% with comments.count as total_comments %}
        <h2>
            {{total_comments}} comment {{total_comments|pluralize}}
        </h2>
    {% endwith %}

    {% for comment in comments %}
        
        <div class="comment">
            <p class="info">
                Comment {{ forloop.counter }} by {{ comment.name }}
                {{ comment.created }}
            </p>
            {{ comment.body|linebreaks }}
        </div>
    
    {% empty %}
        <p>No comments yet</p>

    {% endfor %}
        
    {% include "blog/post/includes/comment_form.html" %}

    {% endblock %}

blog/templates/blog/post/includes/comment_form.html
<h2>Add a new comment</h2>
<form action="{% url "blog:post_comment" post.id %}" method="post">

    {{form.as_p}}
    {% csrf_token %}
    <p><input type="submit" value="Add comment"></p>

</form>

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% block title %}My Blog{% endblock %}
{% block content %}
    <h1>My Blog</h1>
{% for post in posts %}
    <h2>
        <a href="{{post.get_absolute_url}}">
            {{ post.title }}
        </a>
    </h2>
    <p class="tags">Tags: {{post.tags.all|join:","}}</p>
    <p class="date">
        Published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body|truncatewords:30|linebreaks }}
{% endfor %}
{% endblock %}

mainpage/templates/home.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Home</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <h1>Welcome Home</h1>
        <ol>
            <li><a href="/blog/">Blog</a></li>
        </ol>
        <script src="" async defer></script>
    </body>
</html>